### ISSUE TITLE
download the game

### ISSUE THREAD

**Issue by ghost** [Droog71/Quantum-Engineering#4]
excuse me I'm new to github
is it because there are no releases should I download the source and build it myself
or am I ignorant of some way?

**Comment by Droog71** [comment]
Hello. The game can be downloaded here https://droog71.itch.io/quantum-engineering. This link is also in the readme file in the repository. I recommend installing the itch.io desktop app and installing the game with that. https://itch.io/app

**Comment by ghost** [comment]
Thanks for reply
